# This is a sample aws-auth-patch.yml file.
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::204486254309:role/eksctl-eksctl-demo-nodegroup-ng-c-NodeInstanceRole-1BS61ZIZBMU2J
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::204486254309:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-08T16:30:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1772"
  uid: 41419dbd-d5c0-476f-95e9-eb69f31e903f
